TIME_HORIZON: 100
DATA_DIR: ./Data
BASE_LOG_DIR: ./log

experiments:
    2D:
        no_training: 20000
        no_testing : 2000

        hyperparameters:
            learning_rate_init: [0.002]
            learning_rate_final: [0.005]
            n_hidden: [30,40,50,100]
            loss_function: ['MIN','SUM','WSUM','EI']
            batch_size: [1000]
            n_steps: 20
