# LSTM Related
TIME_HORIZON: 100
DATA_DIR: ./Data
BASE_LOG_DIR: ./log
MODEL_DIR: ./trained_models

# Experiment log
SPEARMINT_CONF_BASE_DIR: './spearmint-config'
SKOPT_RESULT_BASE_DIR: './skopt-result'
BENCHMARK_RESULT_BASE_DIR: './benchmark-result'

airfoil_optimization:
    output_dir: './airfoil-opt-result'
    no_alpha: 50
    alpha_range: [-5,5]
    x_start : -1
    lstm_model_2d: 'rnn-cell-2d-1498485717'
    adjustable_y : [1,2,3,4,5]

    y_input_space:
        3: [-0.5,0.2]
        4: [-0.2,0.08]
        5: [-0.1,0.04]


experiments:
    1D:
        np_training: 2000
        no_testing: 2000

        hyperparameters:
            learning_rate_init: [0.005]
            learning_rate_final: [0.0001]
            n_hidden: [100]
            loss_function: ['MIN','OI', 'SUM', 'WSUM_EXPO']
            batch_size: [128]
            n_steps: [20]
            gradient_clipping: [1.0]
            max_x_abs_value: [1.0]
            starting_point:
                - [-1]

    2D:
        no_training: 2000
        no_testing : 2000

        hyperparameters:
            learning_rate_init: [0.005]
            learning_rate_final: [0.0001]
            n_hidden: [100]
            loss_function: ['MIN','OI', 'SUM', 'WSUM_EXPO']
            batch_size: [128]
            n_steps: [20]
            gradient_clipping: [1.0]
            max_x_abs_value: [1.0]
            starting_point:
                - [-1,-1]

    3D:
        np_training: 4000
        no_testing: 2000

        hyperparameters:
            learning_rate_init: [0.005]
            learning_rate_final: [0.0001]
            n_hidden: [100]
            loss_function: ['MIN','OI', 'SUM', 'WSUM_EXPO']
            batch_size: [128]
            n_steps: [20]
            gradient_clipping: [1.0]
            max_x_abs_value: [1.0]
            starting_point:
                - [-1,-1,-1]

    4D:
        np_training: 6000
        no_testing: 2000

        hyperparameters:
            learning_rate_init: [0.005]
            learning_rate_final: [0.0001]
            n_hidden: [100]
            loss_function: ['MIN','OI', 'SUM', 'WSUM_EXPO']
            batch_size: [128]
            n_steps: [20]
            gradient_clipping: [1.0]
            max_x_abs_value: [1.0]
            starting_point:
                - [-1,-1,-1,-1]

    6D:
        np_training: 10000
        no_testing: 2000

        hyperparameters:
            learning_rate_init: [0.005]
            learning_rate_final: [0.0001]
            n_hidden: [100]
            loss_function: ['MIN','OI', 'SUM', 'WSUM_EXPO']
            loss_function: ['SUM']
            batch_size: [128]
            n_steps: [20]
            gradient_clipping: [1.0]
            max_x_abs_value: [1.0]
            starting_point:
                - [-1,-1,-1,-1,-1,-1]
